### ISSUE TITLE
Progress bar causes 'broadcast' error warning in parfor loop

### ISSUE THREAD

**Issue by CNelias** [oliviertrottier/parwaitbar#1]
This not an error but a warning that matlab outputs to tell that the parfor loop cannot be done efficiently. I am working with large arrays, and using the loadbar makes my computing time go from 40s to 16h ...
Is there a way of doing a progress bar that wouldn't break the for loop this way?

**Comment by oliviertrottier** [comment]
Thank you for raising this issue and apologies for slowing down your computation. Could you provide a minimal example with a large array that demonstrates the slow computation? Could you also give some details on the Matlab version and OS that you are using? I have some ideas of what might cause it and the example will help me troubleshoot the source of the slowdown.

**Comment by CNelias** [comment]
I have an image as a tif file, of size 512x512x1300. Doing the following is rather fast:
```
    [h, w, t] = size(image)
    flat_dev = zeros(h*w*t, 5);
    parfor index = 1:h*w*t
        flat_dev(index, :) = image(index) - 5;  %this is not excactly what I do, but a similar operation
    end
 ```
but this 
```
    flat_dev = zeros(h*w*t, 5);
    wb = parwaitbar(h*w*t);
    parfor index = 1:h*w*t
        flat_dev(index, :) = image(index) - 5; 
        wb.progress();
    end
 ```
Throws the warning ```the entire array or structure wb is a broadcast variable, this might result in unnecessary communication overhead.``` this seems to be the reason why the computation is slowed down.

**Comment by oliviertrottier** [comment]
`wb` will be a broadcast variable because the object must be broadcasted to all workers for them to communicate back to the client. This should not cause a lot of overhead though. How many workers are you using?

Also, could you check if the waitbar is using the parallel queue class `parallel.pool.DataQueue`? If it is `wb.UseQueue` should be equal to `true`. Otherwise, the waitbar initializes a temporary file that the workers access and modify allowing them to communicate among themselves. This might cause a lot of overhead depending on how often the file is accessed.

You can also try changing `wb.progress()` to `progress(wb)`. The progress bar should behave the same and the broadcasting warning will be removed.
